#!/bin/bash
# Generated by MuG VRE
cd /absolute/path/MuG/MuG_userdata/MuGUSER57ecf22d91df3/myNuclDynProject

# Running nucldynwf tool ...

echo '# Start time:' $(date) > /absolute/path/MuG/MuG_userdata//MuGUSER57ecf22d91df3/myNuclDynProject/.tool.log

/absolute/path/VM/tool_wrapper/nucleosomeDynamics_wf.py --config /absolute/path/MuG/MuG_userdata//MuGUSER57ecf22d91df3/myNuclDynProject/.config.json --root_dir /absolute/path/MuG/MuG_userdata//MuGUSER57ecf22d91df3 --metadata /absolute/path/MuG/MuG_userdata//MuGUSER57ecf22d91df3/myNuclDynProject/.metadata.json --out_metadata /absolute/path/MuG/MuG_userdata//MuGUSER57ecf22d91df3/myNuclDynProject/.results.json >> /absolute/path/MuG/MuG_userdata//MuGUSER57ecf22d91df3/myNuclDynProject/.tool.log 2>&1

echo '# End time:' $(date) >> /absolute/path/MuG/MuG_userdata//MuGUSER57ecf22d91df3/myNuclDynProject/.tool.log
